### ISSUE TITLE
problem importing bookmarks

### ISSUE THREAD

**Issue by deimidis** [videbar/kobo-highlights#2]
Another problem, if I understand right, the first thing I need to do is `kh import` to create the database. Trying to do that, i received this error:

```
kh import                                                                      ✔  !1/14  
Traceback (most recent call last):
  File "/home/deimidis/.local/bin/kh", line 8, in <module>
    sys.exit(app())
  File "/home/deimidis/.local/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/deimidis/.local/lib/python3.10/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/deimidis/.local/lib/python3.10/site-packages/kobo_highlights/main.py", line 129, in import_highlights
    ereader_bookmarks: list[Bookmark] = query_bookmarks_from_ereader(
  File "/home/deimidis/.local/lib/python3.10/site-packages/kobo_highlights/functions.py", line 147, in query_bookmarks_from_ereader
    volume_id.rsplit("/", 2)[1].replace("_", "").replace(" - ", "-")
IndexError: list index out of range
```

I have a kobo aura h20 updated to last software version.

**Comment by videbar** [comment]
Hi, this is a problem related to how Kobo Highlights finds out the author information of the book. It currently looks at the folder in which the ebbok files are and assumes that this is the author. The reason it does that is that this is the way that [calibre](https://calibre-ebook.com/) stores the ebooks. 

At the moment I didn't realize that this folder structure is only enforce by Calibre, so it naturally doesn't work if you're not exclusively using it for all your ebooks.

I have looked around in the SQLite database and I think I have found a much more robust way of retrieving the author information, I will probably release an update with this change as well as some other small changes to the inner workings of Kobo Highlights in the next few days.

**Comment by deimidis** [comment]
Thanks you, if I can help in any way, let me know. My knowledge on Python is very novice one, but I can try

**Comment by videbar** [comment]
Thanks for the offering :) I just released the new version, which should work for you so I'll close this issue. Feel free to open a new one if you any other problem.

**Comment by deimidis** [comment]
Hi, thanks for the changes. I still had problems, because I use a lot of my own creations with the kobo (converting markdown files to epub through Pandoc). Sometimes I do it very quickly, so I don't add author information. That made your script failed:

```
Traceback (most recent call last):
  File "/home/deimidis/.local/bin/kh", line 8, in <module>
    sys.exit(app())
  File "/home/deimidis/.local/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/deimidis/.local/lib/python3.10/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/deimidis/.local/lib/python3.10/site-packages/kobo_highlights/main.py", line 131, in import_highlights
    ereader_bookmarks: list[Bookmark] = query_bookmarks_from_ereader(
  File "/home/deimidis/.local/lib/python3.10/site-packages/kobo_highlights/functions.py", line 158, in query_bookmarks_from_ereader
    current_bookmark["author"] = content_query_result[1].replace(" - ", "-")
AttributeError: 'NoneType' object has no attribute 'replace'
```
I made this quick change on my local code that makes it work, but maybe you will make something better :):

```
current_bookmark["title"] = content_query_result[0]
        if content_query_result[1] is not None: 
            current_bookmark["author"] = content_query_result[1].replace(" - ", "-")
        else:
            current_bookmark["author"] = 'Sin autor'
```
This add 'Sin autor" to the file and work. Sorry the spanish there.

**Comment by videbar** [comment]
That's a good fix, I just added it to the program. Also, no te preocupes por el español :)
